-------------------------------------------------------------------------------
//NOTIFICATION TABLE 

-- 테이블 삭제
DROP TABLE NOTIFICATION;

-- 테이블 생성
CREATE TABLE NOTIFICATION(
    NOTIFICATION_NO NUMBER(2) NOT NULL,
    NOTIFICATION_CONTENT VARCHAR2(4000) NOT NULL,
    NOTIFICATION_ESSENTIAL VARCHAR2(50) NOT NULL,
    NOTIFICATION_CRE_DATE DATE DEFAULT SYSDATE NOT NULL,
    NOTIFICATION_UPDATE_DATE DATE NOT NULL
);

-- 제약사항 수정
ALTER TABLE NOTIFICATION
ADD CONSTRAINT  NOTIFICATION_NO_PK PRIMARY KEY(NOTIFICATION_NO);

-- 시퀀스 삭제
DROP SEQUENCE NOTIFICATION_NO_SEQ;

-- 시퀀스 생성
CREATE SEQUENCE NOTIFICATION_NO_SEQ
INCREMENT BY 1
START WITH 1;

-- 데이터 삽입
INSERT INTO NOTIFICATION
(NOTIFICATION_NO, NOTIFICATION_CONTENT, NOTIFICATION_ESSENTIAL, NOTIFICATION_UPDATE_DATE)
VALUES (NOTIFICATION_NO_SEQ.NEXTVAL, '1. Dog With You에서 사용된 이미지는 해당 장소와 다를 수 있습니다.', '필수 여부 Y', SYSDATE);

INSERT INTO NOTIFICATION
(NOTIFICATION_NO, NOTIFICATION_CONTENT, NOTIFICATION_ESSENTIAL, NOTIFICATION_UPDATE_DATE)
VALUES (NOTIFICATION_NO_SEQ.NEXTVAL, '2. 리스트에 소개되는 장소는 Dog With You와 어떠한 이해관계도 없으며, Dog With You가 보증하는 가게가 아닙니다.', '필수 여부 N', SYSDATE);

INSERT INTO NOTIFICATION
(NOTIFICATION_NO, NOTIFICATION_CONTENT, NOTIFICATION_ESSENTIAL, NOTIFICATION_UPDATE_DATE)
VALUES (NOTIFICATION_NO_SEQ.NEXTVAL, '3. 본 페이지에 공개된 리스트는 추후 업데이트 될 수 있으며, 업데이트 되는 가게 정보는 저장해둔 리스트에 자동으로 반영됩니다.', '필수 여부 N', SYSDATE);

INSERT INTO NOTIFICATION
(NOTIFICATION_NO, NOTIFICATION_CONTENT, NOTIFICATION_ESSENTIAL, NOTIFICATION_UPDATE_DATE)
VALUES (NOTIFICATION_NO_SEQ.NEXTVAL, '4. Dog With You는 사전 공지 없이 변경, 종료될 수 있습니다.', '필수 여부 Y', SYSDATE);

INSERT INTO NOTIFICATION
(NOTIFICATION_NO, NOTIFICATION_CONTENT, NOTIFICATION_ESSENTIAL, NOTIFICATION_UPDATE_DATE)
VALUES (NOTIFICATION_NO_SEQ.NEXTVAL, '5. 비방 목적으로 작성된 댓글은 임의로 삭제될 수 있습니다.', '필수 여부 Y', SYSDATE);

INSERT INTO NOTIFICATION
(NOTIFICATION_NO, NOTIFICATION_CONTENT, NOTIFICATION_ESSENTIAL, NOTIFICATION_UPDATE_DATE)
VALUES (NOTIFICATION_NO_SEQ.NEXTVAL, '6. 기타 문의사항은 고객센터를 통해 문의 부탁드립니다.', '필수 여부 Y', SYSDATE);

-- 데이터 확인
SELECT NOTIFICATION_NO, NOTIFICATION_CONTENT, NOTIFICATION_ESSENTIAL, NOTIFICATION_CRE_DATE, NOTIFICATION_UPDATE_DATE
FROM NOTIFICATION;

-- 커밋
COMMIT;
-------------------------------------------------------------------------------


