-------------------------------------------------------------------------------
//USER_INFO TABLE 

-- 테이블 삭제
DROP TABLE USER_INFO;

-- 테이블 생성
CREATE TABLE USER_INFO(
    USER_NO NUMBER(6) NOT NULL,
    ID VARCHAR2(50)NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(80) NOT NULL,
    NICKNAME VARCHAR2(100) NOT NULL,
    PHONE VARCHAR2(15)NOT NULL,
    EMAIL VARCHAR2(50) NOT NULL,
    CREATED_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    AUTHORITY VARCHAR2(30) NOT NULL
);

-- 제약사항 수정
ALTER TABLE USER_INFO
ADD CONSTRAINT USER_NO_PK PRIMARY KEY(USER_NO);

ALTER TABLE USER_INFO
ADD CONSTRAINT ID_UK UNIQUE(ID);

ALTER TABLE USER_INFO
ADD CONSTRAINT NICKNAME_UK UNIQUE(NICKNAME);

ALTER TABLE USER_INFO
ADD CONSTRAINT PHONE_UK UNIQUE(PHONE);

ALTER TABLE USER_INFO
ADD CONSTRAINT EMAIL_UK UNIQUE(EMAIL);

-- 시퀀스 삭제
DROP SEQUENCE USER_NO_SEQ;

-- 시퀀스 생성
CREATE SEQUENCE USER_NO_SEQ
INCREMENT BY 1
START WITH 1;

-- 데이터 삽입
INSERT INTO USER_INFO
(USER_NO, ID, PASSWORD, NAME, NICKNAME, PHONE, EMAIL, AUTHORITY)
VALUES (USER_NO_SEQ.NEXTVAL, 'test1', '1234', '테스트1', '테스트용', '01012345678', 'TEST@test.com', 'admin');

INSERT INTO USER_INFO
(USER_NO, ID, PASSWORD, NAME, NICKNAME, PHONE, EMAIL, AUTHORITY)
VALUES (USER_NO_SEQ.NEXTVAL, 'test2', '1234', '테스트2', '테스트용2', '01012345675', 'TEST2@test.com', 'user');

-- 데이터 확인
SELECT *
FROM USER_INFO;

-- 데이터 확인(날짜 데이터)
SELECT USER_NO, ID, TO_CHAR(CREATED_DATE, 'YYYY"년"MM"월"DD"일" HH24:MI:SS')
FROM USER_INFO;

-- 커밋
COMMIT;
-------------------------------------------------------------------------------
    
